- hosts: localhost
  become: true
  tasks:
  - name: Update and Upgrade apt packages
    become: true
    apt:
            upgrade: yes
            update_cache: yes
            cache_valid_time: 86400 #one day
  - name: Install packages
    apt: name={{item}}
    with_items:
            - vim
            - curl
