---
  - name: Install ZSH
    become: yes
    package:
       name:
               - zsh
               - git
       state: present

  - name: Check for oh-my-zsh installation
    stat: "path=~/.oh-my-zsh"
    register: oh_my_zsh_stat

  - name: Check for .zshrc
    stat: "path=~/.zshrc"
    register: zshrc_stat

  - name: Back up .zshrc
    command: mv ~/.zshrc ~/.zshrcbkp
    when: zshrc_stat.stat.exists

  - name: Install OhMyZsh
    #command: sh -c "$(curl -fsSl https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" --unattended
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh
      dest: /home/{{ username_on_host }}/.oh-my-zsh
      force: yes

  - name: Clone new dotfiles to tmp
    git:
            repo: https://github.com/fj9/autobuntu/
            dest: /tmp/autobuntu/

  - name: Copy .zshrc
    command: cp /tmp/autobuntu/roles/zsh/.zshrc /home/{{ username_on_host }}/.zshrc

  - name: Check for aliases
    stat: 
     path: /home/{{ username_on_host }}/aliases.zsh"
    register: aliases_stat

  - name: Back up aliases
    command: mv /home/{{ username_on_host }}/aliases.zsh /home/{{ username_on_host }}/.aliases_bkp.zsh
    when: aliases_stat.stat.exists

  - name: Copy aliases
    command: cp /tmp/autobuntu/roles/zsh/aliases.zsh /home/{{ username_on_host }}/.aliases.zsh

  - name: Get Zsh Path
    command: which zsh
    register: zsh_path

  - name: Set Zsh as default
    become: yes
    user: name={{ username_on_host }} shell={{ zsh_path.stdout }}

  - name: Check which shell
    command: echo $SHELL
    register: check_shell

  - debug:
      msg: "{{ check_shell.stdout }}"
