---
  - name: Install ZSH
    become: yes
    package:
       name:
               - zsh
               - git
       state: present

  - name: Install OhMyZsh
    git:
      repo: https://github.com/ohmyzsh/ohmyzsh
      dest: /home/{{ username_on_host }}/.oh-my-zsh

  - name: Install Z
    get_url:
      url: https://raw.githubusercontent.com/rupa/z/master/z.sh
      dest: /home/{{ username_on_host }}/z.sh
      mode: a+x

  - name: Install Zsh Syntax Highlighting
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git 
      dest: /home/{{ username_on_host }}/zsh-syntax-highlighting

  - name: Install Zsh Auto Seggestion
    git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: /home/{{ username_on_host }}/zsh-autosuggestions

  - name: Clone new dotfiles to tmp
    git:
            repo: https://github.com/fj9/autobuntu/
            dest: /home/{{ username_on_host }}/Downloads/autobuntu

  - name: Copy .zshrc
    copy:
      src: /home/{{ username_on_host }}/Downloads/autobuntu/roles/zsh/.zshrc
      dest: /home/{{ username_on_host }}/.zshrc
      backup: yes

  - name: Copy aliases
    copy:
      src: /home/{{ username_on_host }}/Downloads/autobuntu/roles/zsh/aliases.zsh
      dest: /home/{{ username_on_host }}/aliases.zsh
      backup: yes

  - name: Get Zsh Path
    command: which zsh
    register: zsh_path

    # TODO: This does not work
  - name: Set Zsh as default
    become: yes
    user: name={{ username_on_host }} shell={{ zsh_path.stdout }}

  - name: Check which shell
    command: echo $SHELL
    register: check_shell

  - debug:
      msg: "{{ check_shell.stdout }}"
