  - name: Install ZSH
    apt:
       name: [zsh]
    become: yes
    become_user: root
    become_method: sudo

  - name: Check for oh-my-zsh installation
    stat: "path=~/.oh-my-zsh"
    register: oh_my_zsh_stat

  - name: Check for .zshrc
    stat: "path=~/.zshrc"
    register: zshrc_stat

  - name: Back up .zshrc
    command: mv ~/.zshrc ~/.zshrcbkp
    when: zshrc_stat.stat.exists

  - name: Install OhMyZsh
    shell: wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -0 - | zsh

  - name: Clone new ~/.zshrc
    git:
      repo=https://github.com/fj9/autobuntu/roles/zsh.zshrc
      dest=~/.zshrc
  
  - name: Check for aliases
    stat: "path=~/alises.zsh"
    register: aliases_stat

  - name: Back up aliases
    command: mv ~/aliases.zsh ~/.aliases_bkp.zsh
    when: aliases_stat.stat.exists
  
  - name: Clone aliases
    git:
      repo=https://github.com/fj9/autobuntu/roles/zsh/aliases.zsh
      dest=~/aliases.zsh
