---
  - name: Download Google Chrome Deb
    get_url:
            url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb 
            dest: /home/{{ username_on_host }}/Downloads/

  - name: Install google chrome
    apt: 
      deb: "/home/{{ username_on_host }}/Downloads/google-chrome-stable_current_amd64.deb"
